import type { Task, Project, LlmResponse } from "./types"

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Prepare presentation for client meeting",
    description: "Create slides and talking points for the quarterly review meeting with ABC Corp.",
    priority: "high",
    estimatedTime: "2 hours",
    timeSlot: "9:00 AM - 11:00 AM",
    dueDate: "today",
    completed: false,
    subtasks: [
      { title: "Gather performance metrics", completed: true },
      { title: "Create slide deck", completed: false },
      { title: "Prepare talking points", completed: false },
      { title: "Review with team", completed: false },
    ],
  },
  {
    id: "task-2",
    title: "Finish project proposal",
    description: "Complete the proposal document for the new marketing campaign.",
    priority: "high",
    estimatedTime: "1.5 hours",
    timeSlot: "1:00 PM - 2:30 PM",
    dueDate: "today",
    completed: false,
    subtasks: [
      { title: "Write executive summary", completed: true },
      { title: "Complete budget section", completed: false },
      { title: "Add timeline", completed: false },
    ],
  },
  {
    id: "task-3",
    title: "Weekly team check-in",
    description: "Virtual meeting with the product team to discuss progress and blockers.",
    priority: "medium",
    estimatedTime: "45 min",
    timeSlot: "3:00 PM - 3:45 PM",
    dueDate: "today",
    completed: false,
  },
  {
    id: "task-4",
    title: "Review design mockups",
    description: "Provide feedback on the new feature design mockups from the design team.",
    priority: "medium",
    estimatedTime: "1 hour",
    timeSlot: "4:00 PM - 5:00 PM",
    dueDate: "today",
    completed: false,
  },
  {
    id: "task-5",
    title: "Update documentation",
    description: "Update the user guide with the latest feature changes.",
    priority: "low",
    estimatedTime: "1.5 hours",
    dueDate: "upcoming",
    completed: false,
  },
  {
    id: "task-6",
    title: "Research competitors",
    description: "Analyze competitor products and create a comparison report.",
    priority: "medium",
    estimatedTime: "2 hours",
    dueDate: "upcoming",
    completed: false,
  },
  {
    id: "task-7",
    title: "Send follow-up emails",
    description: "Send follow-up emails to clients from last week's conference.",
    priority: "high",
    estimatedTime: "30 min",
    dueDate: "upcoming",
    completed: false,
  },
  {
    id: "task-8",
    title: "Prepare monthly report",
    description: "Compile data and prepare the monthly performance report.",
    priority: "high",
    estimatedTime: "3 hours",
    dueDate: "upcoming",
    completed: false,
  },
  {
    id: "task-9",
    title: "Update website content",
    description: "Update the company website with new product information.",
    priority: "low",
    estimatedTime: "1 hour",
    dueDate: "completed",
    completed: true,
  },
  {
    id: "task-10",
    title: "Conduct user interviews",
    description: "Interview 5 users to gather feedback on the new feature.",
    priority: "medium",
    estimatedTime: "2.5 hours",
    dueDate: "completed",
    completed: true,
  },
]

export const mockProjects: Project[] = [
  {
    id: "project-1",
    name: "Website Redesign",
    description: "Redesign the company website with a modern look and improved UX",
    color: "#f43f5e",
    totalTasks: 12,
    completedTasks: 8,
  },
  {
    id: "project-2",
    name: "Q3 Marketing Campaign",
    description: "Plan and execute the Q3 marketing campaign for product launch",
    color: "#8b5cf6",
    totalTasks: 18,
    completedTasks: 6,
  },
  {
    id: "project-3",
    name: "Mobile App Development",
    description: "Develop a mobile app version of our main product",
    color: "#3b82f6",
    totalTasks: 24,
    completedTasks: 10,
  },
  {
    id: "project-4",
    name: "Customer Research",
    description: "Conduct research to better understand customer needs",
    color: "#10b981",
    totalTasks: 8,
    completedTasks: 5,
  },
  {
    id: "project-5",
    name: "Product Analytics",
    description: "Implement analytics to track product usage and performance",
    color: "#f59e0b",
    totalTasks: 10,
    completedTasks: 2,
  },
]

export const mockLlmResponse: LlmResponse = {
  message:
    "I've analyzed your tasks and created a structured plan. I've prioritized the presentation preparation as high priority since client meetings are typically important. I've also broken down the tasks into manageable chunks with time estimates.",
  tasks: [
    {
      id: "gen-task-1",
      title: "Prepare presentation for client meeting",
      description:
        "Create a comprehensive presentation for the upcoming client meeting, focusing on key achievements and future plans.",
      priority: "high",
      estimatedTime: "2 hours",
      timeSlot: "9:00 AM - 11:00 AM",
      dueDate: "today",
      completed: false,
      subtasks: [
        { title: "Gather performance metrics and data", completed: false },
        { title: "Create slide deck with key points", completed: false },
        { title: "Prepare talking points and script", completed: false },
        { title: "Practice presentation at least twice", completed: false },
      ],
    },
    {
      id: "gen-task-2",
      title: "Finalize quarterly report",
      description: "Complete the quarterly report with all financial data and performance metrics.",
      priority: "high",
      estimatedTime: "1.5 hours",
      timeSlot: "1:00 PM - 2:30 PM",
      dueDate: "today",
      completed: false,
      subtasks: [
        { title: "Update financial section with latest figures", completed: false },
        { title: "Add executive summary", completed: false },
        { title: "Review for accuracy and completeness", completed: false },
      ],
    },
    {
      id: "gen-task-3",
      title: "Grocery shopping",
      description: "Purchase groceries for the week, focusing on healthy meal options.",
      priority: "medium",
      estimatedTime: "1 hour",
      timeSlot: "5:30 PM - 6:30 PM",
      dueDate: "today",
      completed: false,
      subtasks: [
        { title: "Make shopping list", completed: false },
        { title: "Check pantry for existing items", completed: false },
        { title: "Visit grocery store", completed: false },
        { title: "Put away groceries", completed: false },
      ],
    },
    {
      id: "gen-task-4",
      title: "Exercise session",
      description: "Complete a 30-minute workout to maintain health and energy levels.",
      priority: "low",
      estimatedTime: "30 min",
      timeSlot: "7:00 AM - 7:30 AM",
      dueDate: "today",
      completed: false,
    },
  ],
}
